apiVersion: batch/v1
kind: Job
metadata:
  name: "hello"
  labels:
    hello: world
  annotations: {}
    #"helm.sh/hook": post-install
    #"helm.sh/hook-weight": "-5"
    #"helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: "alpine:3.3"
        command: ["/bin/sleep","21"]
